config-version: 1

database:
  type: SQLite
  host: localhost
  port: 3306
  name: vite_list
  username: root
  password: Admin@123

messages:
  prefix: "&7[&5ViteList&7] &k&lii"
  no-permission: "%prefix% &cInsufficient &7permissions"
  server-not-found: "%prefix% &7Specified server &f%server% &7does &cNot &7exist"
  wrong-usage: "%prefix% &cWrong &7usage of command, use &7&l/whitelist help"
  reload-success: "%prefix% &7reload &aSuccessful"
  reload-fail: "%prefix% &7reload &cFailed"
  enable-global: "%prefix% &7Whitelist has been &aEnabled &7globally"
  enable-server: "%prefix% &7Whitelist has been &aEnabled &7in &f%server%"
  disable-global: "%prefix% &7Whitelist has been &cDisabled &7globally"
  disable-server: "%prefix% &7Whitelist has been &cDisabled &7in &f%server%"
  add-global: "%prefix% &7User &f%user% &7has been &aAdded &7to global whitelist"
  add-server: "%prefix% &7User &f%user% &7has been &aAdded &7to whitelist in &f%server%"
  remove-global: "%prefix% &7User &f%user% &7has been &cRemoved &7from global whitelist"
  remove-server: "%prefix% &7User &f%user% &7has been &cRemoved &7from whitelist in &f%server%"
  kick: "&7You're &cNot &7whitelisted at this server"
  server-switch: "%prefix% &7You are &cNot &7whitelisted in this server"
